### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jasbindar-singh** [jasbindar-singh/webpack-react#1]
- [x] Style linter
- [x] General linter
- [x] CSS in a separate file for visualization
- [x] Hot reloads
- [ ] Minifiers/Compressors style/js(postcss/brotli/gzip)
- [ ] Auto webp images(postcss plugins) (Possible not a good idea to store images on codebase)
- [ ] Auto sprites postcss (Mere Usecase might try later)
- [x] Development environment(dev/prod)
- [x] Analyzers webpack
- [x] Assets loader
- [ ] Performance and Optimizations
